### ISSUE TITLE
How can I use this on macOS?

### ISSUE THREAD

**Issue by NightMachinery** [jolivain/glslsandbox-player#1]

**Comment by jolivain** [comment]
Hi,

There is currently no direct OSX support in glslsandbox-player, as I don't have access to such a system.  I'm not even sure that OSX directly supports GLES, as it's initially targeting mobile/embedded platforms with iOS.  Moreover, Apple seems to deprecate Khronos APIs, in favor to Metal.

You could try to to link glslsandbox-player against the ANGLE project http://angleproject.org/ that is translating GLES calls to desktops APIs (GL).  I see there is some Mac OS X support in progress.

You could test one ANGLE sample application before doing anything, like:
https://github.com/google/angle/tree/master/samples/hello_triangle

I see also there is some OSX OpenGLES support in SDL2 library:
http://hg.libsdl.org/SDL/file/f1084c419f33/src/video/cocoa

You could try to use the SDL2 support of glslsandbox-player, compiling with `./configure --with-native-gfx=sdl2 && make`), provided you have a working SDL2 with GLES library.

Finally, some OSX native windowing support may be needed, following:
https://github.com/jolivain/glslsandbox-player#adding-a-new-native-windowing-library-to-glslsandbox-player

Please, let me know if you manage to get something working on OSX.

Best regards,

Julien.

**Comment by jolivain** [comment]
I finally had a chance to get my hands on an OS X system. I added a very basic support for Cocoa, using Google ANGLE, as I initially suggested.  See: https://github.com/jolivain/glslsandbox-player#notes-on-the-apple-cocoa-os-x-native-windowing
