### ISSUE TITLE
ThankYou!  How make window launch below others?

### ISSUE THREAD

**Issue by clort81** [jolivain/glslsandbox-player#3]
ExplosiveTurbulentNoise!  Behind my windows!  It's finally possible!

http://0x0.st/iixa.mp4
fullscreen recording of desktop :) http://0x0.st/ii3N.mp4
~16-20% cpu from Xorg

./glslsandbox-player -E -N -W 3840 -H 2140 -t 20 -w 6 -s 0.3 -q -Q high -R 4 -P 33.3333 -S ExplosiveTurbulentNoise

Negligble cpu/gpu load on my nvidia jetson nano!

This is SO GREAT.

Trying to launch in my own batch script, below other windows...
```
#!/bin/bash
oldps1=$PS1
while true;
do
 randomfile=$(( $RANDOM % 99999 ))
 myshad=`ls | shuf -n 1`
echo -ne "\033]0;$myshad\007"
echo $myshad
glslsandbox-player  -t 20  -B -W 3840 -H 2140 -w 6 -s 0.09 -q -Q medium -R 10 -P 66.6666 -m -F $myshad&
sleep 2s
wmctrl -r "glslsandbox-player" -b add,below
sleep 2s
wmctrl -r "glslsandbox-player" -b add,below
sleep 16s
done
PS1=$oldps1
```
I can't seem to get the script to push the created window below the others, but it works when i call wmctrl in another terminal.

Can it be possible for glslsandbox-player to tell window manager "put window below other windows"?
Thanks!

**Comment by jolivain** [comment]
Hi,

According to the wmctrl help (when launching "wmctrl -h"), window selection using "-r" option seems to be case insensitive AND a substring search in the window list. It takes the first window that include the specified string in window title. See the output of "winctrl -l". When having a lot of windows, it's likely several windows include this substring in its title (e.g. web browser, terminals, ...). So it's possible that in your case, the wrong window is selected.

wmctrl has the "-F" option, to change the window selection behavior to an exact, case sensitive string match.

So in your script, just adding "-F" should always select the correct window.  Ex:

    wmctrl -F -r glslsandbox-player -b add,below

I successfully tested that on Fedora 31, wmctrl 1.07.

In the meantime, I'll try to add this feature in the code itself.

Thanks for the suggestion!
