### ISSUE TITLE
cannot find glslsandbox-shaders.c

### ISSUE THREAD

**Issue by dongjunkun** [jolivain/glslsandbox-player#4]
glslsandbox-shaders.c file not exist

**Comment by jolivain** [comment]
Hi,

The glslsandbox-shaders.c file is generated from here:
https://github.com/jolivain/glslsandbox-player/blob/7ad3aa0c6f5e23519acda247ee0c14a9add565c1/src/Makefile.am#L36

It will be generated if you follow the instructions from here:
https://github.com/jolivain/glslsandbox-player/blob/7ad3aa0c6f5e23519acda247ee0c14a9add565c1/README.md#quick-start

    git clone https://github.com/jolivain/glslsandbox-player.git
    cd glslsandbox-player
    autoreconf -vfi
    ./configure
    make

Thanks!
