### ISSUE TITLE
Mediump precision is insufficient for Fibber28Scene1 and MapleLeaSDF

### ISSUE THREAD

**Issue by liuliuliu11111** [jolivain/glslsandbox-player#6]
Hi
We meet some precision issues with the default mediump in shader Fibber28Scene1 (63414.0.frag) and MapleLeaSDF (56789.0.frag).
But highp can pass. (use -Q high), failing with lowp as well.
**./src/glslsandbox-player -W 640 -H 320 -R 8 -t 3 -S Fibber28Scene1** 

After some debug, we found that the default mediump **(float16)** is insufficient for the two shader and cause an infinite loop.
Details:
We add some debug information in the shadow function in shader and there is an infinite loop of **t+=h**: 120.625000 (t) + 0.015813 (h) -> 120.625000 (t)
The shading language spec: https://www.khronos.org/files/opengles_shading_language.pdf requires 2^(-10) relative precision for mediump. It seems 0.015813 / 120.625000 = 0.00013109, the number is far more small than 2^(-10). So I thinks the two shader case has some precision issue for the default mediump. Could you please have a check and fix will be appreciated.

float shadow(in vec3 ro, in vec3 rd, float mint, float maxt, float shadowAmbient)
{
    
    float t = 0.1;
    for(float _ = 0.0; _ == 0.0; _ += 0.0)
    {
        if (t >= maxt) {
        	return 1.0;
        }
        float h = scene(ro + rd*t, rd).x;
        if( h<0.01 )
            return shadowAmbient;
        t += h;
    }
    return 1.0;
}

**Comment by jolivain** [comment]
Fixed.  Thanks for reporting the issue!
